### ISSUE TITLE
Question on running joindemo.py

### ISSUE THREAD

**Issue by lcipolina** [michele-segata/plexe-pyapi#1]
Hello, thanks for this library. 

I am trying to run joindemo.py:

`$python /home/alpha/plexe-pyapi/examples/joindemo.py`

I get the following error:

```
Retrying in 1 seconds
Loading configuration... done.
No Plexe API implementation found for SUMO UNKNOWN
Traceback (most recent call last):
  File "/home/alpha/plexe-pyapi/examples/joindemo.py", line 217, in <module>
    main(True, False)
  File "/home/alpha/plexe-pyapi/examples/joindemo.py", line 159, in main
    plexe = Plexe()
  File "/home/alpha/plexe-pyapi/examples/plexe.py", line 110, in __init__
    raise Exception()
Exception
```

Thank you very much!

**Comment by michele-segata** [comment]
Which version of SUMO are you running? I tried the join demo with SUMO 1.6.0 and it properly works.

**Comment by lcipolina** [comment]
Hi Michele, thank you very much for your quick reply

Happens that with my SUMO 1.6.0 I was getting the error on your FAQS
http://plexe.car2x.org/faq/

`Unknown cfmodel when parsing vtype 'vtypeauto'`

So I uninstalled all the SUMOs and used your SUMO-PLEXE

My paths are as follows:
```
export SUMO_HOME=/home/alpha/src/plexe-sumo
export PATH=$PATH:~/src/plexe-sumo/bin
```

See attached fot my SUMO version

<img width="330" alt="which sumo" src="https://user-images.githubusercontent.com/5190890/87903221-801bd900-ca29-11ea-882b-f1a86b13ea6c.PNG">

**Comment by lcipolina** [comment]
ok, so now I've installed SUMO 1.6 and change the SUMO_HOME env variable to SUMO's regular version.

I still get the following error... I wonder if everything got compiler properly on installation...

`(plexe) alpha@alpha:~/plexe-pyapi$ python /home/alpha/plexe-pyapi/examples/joindemo.py`

```
 Retrying in 1 seconds
Loading configuration ... done.
No Plexe API implementation found for SUMO 1.6.0
Traceback (most recent call last):
  File "/home/alpha/plexe-pyapi/examples/joindemo.py", line 217, in <module>
    main(True, False)
  File "/home/alpha/plexe-pyapi/examples/joindemo.py", line 159, in main
    plexe = Plexe()
  File "/home/alpha/plexe-pyapi/examples/plexe.py", line 110, in __init__
    raise Exception()
Exception
```

**Comment by michele-segata** [comment]
Can you check that your python APIs are at the latest version, i.e., commit 9a9416e?
Because I've added a default fallback in case the SUMO version doesn't match. So if no compatible SUMO version handler is found, there is one handler that it is being used as default.
[Here](https://github.com/michele-segata/plexe-pyapi/blob/master/plexe/plexe_imp/plexe_sumo_eclipse.py#L37) is the code indicating that the `plexe_sumo_eclipse` is the default implementation, while [here](https://github.com/michele-segata/plexe-pyapi/blob/master/plexe/plexe.py#L107) is the portion of the code that selects the default implementation if a match on the version is not found.

**Comment by lcipolina** [comment]
Hi Michele, yes, I've downloaded the Repo today... (I see that your changes are back from 2 yrs ago.)

I can try to debug the code and see where the version is failing

**One question.... what SUMO_HOME (and any other SUMO related env variable) should be on my .bashrc?**

Thanks! and sorry for having so many questions!

**Comment by michele-segata** [comment]
> I can try to debug the code and see where the version is failing

This would really help me fixing the bug. Just put a couple of `print` around the place where the default implementation should be selected and try to see why it is not selected.

> 
> **One question.... what SUMO_HOME (and any other SUMO related env variable) should be on my .bashrc?**

You should have `SUMO_HOME` in order for python to find the libraries. This is not Plexe specific, this is required by SUMO.

> This is my latest configuration (I reverted to SUMO 0.32)

I would avoid using SUMO 0.32.0. I would keep 1.6.0 and try to find why the Python API are not "accepting" it. It should be an easy fix.
 
> ```
> export SUMO_HOME=/usr/share/sumo 
> #export SUMO_HOME=/home/alpha/src/plexe-sumo
> export PATH=$PATH:/home/alpha/Downloads/omnetpp-5.6.2/bin
> export PATH=$PATH:~/src/plexe-sumo/bin
> ```

Careful here! You are mixing up different installations. You have the standard SUMO in `/usr/share` and `plexe-sumo` in `~/src/plexe-sumo`. If you don't plan to modify SUMO, just keep the binary version and get rid of any reference to `plexe-sumo` in your `.bashrc` file.

**Comment by lcipolina** [comment]
ok, I commented the` plexe-sumo` in .bashrc and I still get the same error.
(we can discuss this later, I was trying to run the Plexe tutorials, which I succeded, but thought this API will be more handy as it's python-based)

To give you some color, my research is to do some Platooning + Reinforcement Learning. So a python API sounds great.

**Just to rule out the obvious before debugging, is this meant to run in Python 3?**

**Comment by michele-segata** [comment]
> **Just to rule out the obvious before debugging, is this meant to run in Python 3?**

Yes, I am using it with Python 3.

**Comment by lcipolina** [comment]
I am debugging with Pycharm... 
I see the following
<img width="374" alt="plexe-error" src="https://user-images.githubusercontent.com/5190890/87919743-3f7e8880-ca46-11ea-8e0a-56ec3acc0e74.PNG">

**Comment by michele-segata** [comment]
This is very strange. I tried to change the library used to perform the import as the old one was marked as obsolete. Can you fetch the changes and re-install the package with
```
pip install --user --upgrade .
```

**Comment by lcipolina** [comment]
Michele, thank you very much for all the time you've put into solving this issue. 
I've finally made it work!  I'll close the issue since it's resolved.

These were my steps in case someone find it useful. 

**# Download the library**
# cd to the folder you want to download the library
>> git clone  https://github.com/michele-segata/plexe-pyapi.git

**# Build**
(outside any conda environment)
>> cd plexe-pyapi
>> sudo pip install .   (notice the dot at the end)
>> pip install --user .

**#Usage**
>> conda activate plexe (I've build an environment to install q5)
>> cd ~plexe-pyapi/examples
>> SUMO_HOME=/usr/share/sumo/  #set the PATH environment for latest SUMO version (in case you have other versions installed. )
>>  python joindemo.py

**Comment by michele-segata** [comment]
Just a quick note. You shouldn't do both
> sudo pip install .

and

> pip install --user .

You either have to choose whether to install it system-wide (run the first) or install it for the current user only (run the second).

**Comment by lcipolina** [comment]
Thank you very much for all this time Michele. I will create a tutorial for you and make a "Pull request" in case you find it useful for other folks navigating this page.
