### ISSUE TITLE
Working of Plexe API in Plexe Instant

### ISSUE THREAD

**Issue by prasuka4** [michele-segata/plexe-pyapi#10]
Hi Michele,
This is Prashanth, PhD student in Network engineering from Polytechnic University of Catalonia (UPC), SPAIN. I'm using Plexe Instant 3.0 for creating platoon scenarios. Now I'm trying to use Plexe API for connecting TRACI with Plexe and alter the route, lanes and vehicle connections.
But while doing this everytime it is showing as "ModuleNotFoundError: No module named 'plexe'".

Could you please let me know how to resolve this issue. Below is the screenshot that tells the location of PlexeAPI.

![image](https://user-images.githubusercontent.com/48856575/158415978-6b7d0f62-a9e8-49af-af82-572667e14ffe.png)

**Comment by michele-segata** [comment]
Dear Prashanth,

Instant Plexe does not ship with Python APIs, as it is thought to give the users a pre-configured VM including OMNeT++, Veins, SUMO, and Plexe itself. In fact, to use the Python APIs you just need SUMO (and the Python APIs of course), which is easy to install natively on any machine.
It looks to me that you have been cloning the Python APIs within the Instant-Plexe VM but, looking at the error, it seems like you haven't been installing them via `pip`. Did you follow all the instructions in the [README.md](https://github.com/michele-segata/plexe-pyapi#readme) file? Did you install the APIs using
```bash
pip install --user .
```
?

**Comment by prasuka4** [comment]
Thank you very much for the support there was some issue in my VM hence it was not working even though i have followed README.md. Now i'm able to work around without any error.
Thank you once again
