### ISSUE TITLE
hou to generate new platoon vehicles with new route

### ISSUE THREAD

**Issue by zhaotuo0815** [michele-segata/plexe-pyapi#11]
Hello developers, in the demo case you gave, the vehicle driving path is not defined in the functions add_vehicles and add_platooning_vehicle for generating vehicles. If I now have a new route (already declared in the rou file), how can I set it on the new path for generating platoon vehicles?

**Comment by michele-segata** [comment]
The route is hardcoded in [this method here](https://github.com/michele-segata/plexe-pyapi/blob/112848c20eb84da82efd87e771df350c7b266c09/examples/utils.py#L62). As you can see it refers to a route `platoon_route` which is [defined here](https://github.com/michele-segata/plexe-pyapi/blob/112848c20eb84da82efd87e771df350c7b266c09/examples/cfg/freeway.rou.xml#L15). You can edit the method and add a parameter called `route` and substitute the hardcoded value.

**Comment by zhaotuo0815** [comment]
> The route is hardcoded in [this method here](https://github.com/michele-segata/plexe-pyapi/blob/112848c20eb84da82efd87e771df350c7b266c09/examples/utils.py#L62). As you can see it refers to a route `platoon_route` which is [defined here](https://github.com/michele-segata/plexe-pyapi/blob/112848c20eb84da82efd87e771df350c7b266c09/examples/cfg/freeway.rou.xml#L15). You can edit the method and add a parameter called `route` and substitute the hardcoded value.

thank you so much
