### ISSUE TITLE
a platoon inserts another platoon

### ISSUE THREAD

**Issue by midfielder21** [michele-segata/plexe-pyapi#19]
Hello author, the code you provided is very helpful to me, thank you very much!
In addition, I would like to ask if it is possible to implement the insertion of a platoon into another platoon based on the example you provided? Similar to joindemo, but the single vehicle becomes a platoon.

**Comment by michele-segata** [comment]
Sure. There is already an example maneuver implemented. If you follow the instructions for the join maneuver simulation but you launch the [MergeManeuver](https://github.com/michele-segata/plexe/blob/4ca9cd10456acf1a2b8946c5cb392ff00bbde6a9/examples/joinManeuver/omnetpp.ini#L215) config instead, you will see a merge of two platoons.
