### ISSUE TITLE
I can't find CC_VehicleVariables.h file in Plexe

### ISSUE THREAD

**Issue by hosseinihalimeh** [michele-segata/plexe-pyapi#20]
In the link https://plexe.car2x.org/tutorial/example2/ the file CC_VehicleVariables.h is used, I can't find it in the plexe folder

**Comment by hosseinihalimeh** [comment]
@michele-segata Hi Michael, can you please help me with this

**Comment by michele-segata** [comment]
https://github.com/eclipse-sumo/sumo/blob/v1_20_0/src/microsim/cfmodels/CC_VehicleVariables.h

**Comment by hosseinihalimeh** [comment]
Hi Michael and thank you very much for taking the time to answer the questions. I really appreciate it.
In the second example of the Plex tutorial,https://plexe.car2x.org/tutorial/example2/
Where should this code be placed?
I have placed it in the initializeControllers() function.
But I am getting this error when building Plexe
![1](https://github.com/user-attachments/assets/5bcd1fb5-d0bd-4fe1-8b73-9f029ec26f3d)
<img width="479" alt="2" src="https://github.com/user-attachments/assets/74b75da2-cc1a-4019-aca9-e9eaf66dbee1">
![Uploading 2.png…]()

@michele-segata

**Comment by michele-segata** [comment]
As written at the beginning, the tutorial is for an older version of Plexe. For the newer version you should edit [here](https://github.com/michele-segata/plexe/blob/3e4f83d11ca67f138ed48a763e23e75842f559fa/src/plexe/mobility/TraCIBaseTrafficManager.cc#L66), [here](https://github.com/michele-segata/plexe/blob/3e4f83d11ca67f138ed48a763e23e75842f559fa/src/plexe/scenarios/BaseScenario.cc#L96), and [here](https://github.com/michele-segata/plexe/blob/3e4f83d11ca67f138ed48a763e23e75842f559fa/src/plexe/scenarios/BaseScenario.cc#L111), besides `CC_Const.h`
