### ISSUE TITLE
Question: Is there anyway that we can generate results for analysis? 

### ISSUE THREAD

**Issue by SafrasIqbal** [michele-segata/plexe-pyapi#3]
Hi Michele.

The PlexeAPI seems a feasible option for me to generate custom platoon scenarios. I just wondering will there be an option for me to generate results for analysis. Will the PlexeAPI will be enhanced to results generation?  or will you suggest me a lead for me to try out a way to generate the results? Thank you. 

Regards,

Safras

**Comment by michele-segata** [comment]
The python API only control the simulation. If you need to collect results, you need to implement that yourself inside the simulation.
Just remember that, if you choose the python API, you only have platooning models and no communication models.

**Comment by SafrasIqbal** [comment]
Hi Michele,

Oh ok got it. I probably need the communication model as well.  Thanks for the info. 

Regards,

Safras

**Comment by SafrasIqbal** [comment]
query answered. hence closing
